kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mq1route 
  namespace: mq 
spec:
  host: tlsaut.chl.mq.ibm.com
  to:
    kind: Service
    name: mq-aut-ibm-mq 
  port:
    targetPort: 1414
  tls:
    termination: passthrough
